# Generated by Django 5.1.1 on 2024-09-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0002_alter_watch_purchased_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='purchased_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
